#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --disable-systemd-logind \
    --disable-xwayland \
    --disable-unit-tests \
    --enable-glx \
    --enable-dri \
    --enable-dri2 \
    --enable-dri3 \
    --disable-glamor \
    --enable-xorg \
    --enable-config-udev \
    --enable-config-udev-kms \
    --with-sha1=libcrypto \
    --with-systemd-daemon=off

make
make DESTDIR="$1" install

rm -f "$1/usr/share/X11/xorg.conf.d/10-evdev.conf"
