#!/bin/sh -e

patch -p1 < musl-fix-cplusplus-decls.patch

make \
    DEFAULTFONTDIR=/usr/share/figlet/fonts \
    all

make \
    DESTDIR="$1" \
    BINDIR=/usr/bin \
    MANDIR=/usr/share/man \
    DEFAULTFONTDIR=/usr/share/figlet/fonts \
    install
