#!/bin/sh -e

patch -p1 < rounded-corners.patch

make PREFIX=/usr
make DESTDIR="$1" PREFIX=/usr install

# Yuck.
rm -rf "$1/usr/share/fish"
rm -rf "$1/usr/share/zsh"
rm -rf "$1/usr/share/bash-completion"
#rm -rf "$1/usr/share/doc"
rm -rf "$1/usr/share/xsessions"
