#!/bin/sh -e

patch -p0 < atomic.patch

cd build_unix

../dist/configure \
    --prefix=/usr \
    --enable-compat185 \
    --enable-stl \
    --enable-cxx \
    --enable-dbm

make LIBSO_LIBS=-lpthread
make DESTDIR="$1" install
